config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "languages#index"
  resources :languages, only: [:show, :create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  resources :repos, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :repo
  validates :repo, uniqueness: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :repos, dependent: :destroy
  validates :name, uniqueness: true
end

app/models/repo.rb
class Repo < ApplicationRecord
    belongs_to :language
    has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def create
    @bookmark = Bookmark.new(repo_id: params[:repo])
    @bookmark.save
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_path
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @languages = Language.all
    @language = Language.new
  end

  def create
    @languages = Language.all
    @language = Language.new(language_params)
    access_token = ENV['GH_ACCESS_TOKEN']
    url = "https://api.github.com/search/repositories?q=language:#{@language.name}&sort=stars&per_page=5"
    request = HTTParty.get(
      url,
      headers: { Authorization: "Bearer #{access_token}" }
    )
    request_hash = request.to_h
    items = request_hash['items']
    create_repos(items, @language)
    if @language.save
      redirect_to :root
    end
  end

  def destroy
    @language = Language.find(params[:id])
    @language.destroy
    redirect_to :root
  end

  private

  def language_params
    params.require(:language).permit(:name)
  end

  def create_repos(items, language)
    items.each do |item|
      repo_owner = item['owner']['login']
      repo_name = item['name']
      repo_languages = HTTParty.get("https://api.github.com/repos/#{repo_owner}/#{repo_name}/languages").to_h.keys
      repo = Repo.new(
        full_name: repo_name,
        owner: repo_owner,
        description: item['description'],
        api_url: item['api_url'],
        html_url: item['html_url'],
        ssh_url: item['ssh_url'],
        languages: repo_languages,
        stars: item['stargazers_count'],
        created: item['created_at'],
        updated: item['updated_at']
      )
      repo.language = language

      repo.save
    end
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
    def index
        @repos = Repo.order(:languages)
    end

    def show
        @repo = Repo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/bookmarks/index.html.erb
<h1>Favorite repositories</h1>
    <% @bookmarks.each do |bookmark| %>
    <h3><%= bookmark.repo.full_name %></h3>
    <p><%= bookmark.repo.description %></p>
    <%= link_to 'View details', repo_path(bookmark.repo) %>
    <%= link_to 'Remove from favorites', bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
<% end %>

app/views/languages/index.html.erb
<h1>iCertus backend dev test</h1>
<p>Select from one of the languages below to get top 5 repositories from github</p>

<%= simple_form_for Language.new do |f| %>
    <%= f.select :name, ['Ruby', 'Haskell', 'C', 'JavaScript', 'Python']%>
    <%= f.submit 'Get Repos!' %>
<% end %>

<%= link_to 'Favorite repos', bookmarks_path %>

<div class="langs-index">
    <% @languages.all.each do |language| %>
        <div class="lang">
            <h2 style="background-color: rgba(40, 40, 40, 0.2); margin-bottom: 0"><%= language.name %></h2>
            <%= link_to 'Delete', language_path(language), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
            <% language.repos.each do |repo| %>
                <div class="repo" style="margin: 2rem 1rem">
                    <h3><%= repo.full_name %></h3>
                    <p><%= repo.description %></p>
                    <%= link_to 'View details', repo_path(repo) %>
                    <%= link_to 'Favorite', bookmarks_path(repo: repo), data: {turbo_method: :post, turbo_confirm: 'Add to favorites?'} %>
                </div>
            <% end %>
        </div>  
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apiforgods</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repos/show.html.erb
<h1><%= @repo.full_name %></h1>
<h3>Created by: <%= @repo.owner %></h3>
<p>Description: <%= @repo.description %></p>
<a href=<%=@repo.html_url%>>View on github</a>
<p>SSH to clone: <%= @repo.ssh_url %></p>
<p>Languages: <%=JSON[@repo.languages].join(', ')%></p>
<p>Stars: <%= @repo.stars %></p>
<p>Created at: <%= @repo.created.to_datetime.strftime("%d/%m/%Y %H:%M") %></p>
<p>Last updated: <%= @repo.updated.to_datetime.strftime("%d/%m/%Y %H:%M") %></p>
<%= link_to 'Favorite', bookmarks_path(repo: @repo), data: {turbo_method: :post, turbo_confirm: 'Add to favorites?'} %>